name: Build sukebe and upload binaries
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build sukebe and upload binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure main requirements are installed
        id: core
        run: pip3 install httpx loguru nuitka

      - name: Compile to binary
        id: owo
        run: cd src && python3 -m nuitka --follow-imports --include-plugin-directory=sukebe __main__.py
      
      - name: Rename binary
        id: uwu
        run: mv src/__main__.bin src/sukebe.bin

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: Sukebe
          files: src/sukebe.bin