name: Build sukebe and upload binaries
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build sukebe and upload binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure main requirements are installed
        id: core
        run: pip3 install httpx loguru nuitka
      
      - name: Get version
        id: version
        run: echo "::set-output name=sukebe_version::$(cat pyproject.toml | grep version | sed -e s/[^0-9.]//g)"

      - name: Compile to binary
        id: owo
        run: cd src && python3 -m nuitka --follow-imports --include-plugin-directory=sukebe __main__.py
      
      - name: Rename binary
        id: uwu
        run: mv src/__main__.bin src/sukebe.bin

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: sukebe_v${{ steps.version.outputs.sukebe_version }}
          prerelease: false
          title: sukebe ${{ steps.version.outputs.sukebe_version }}
          files: src/sukebe.bin